apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - patch-gpu.yaml

namePrefix: aws-
commonLabels:
  cluster-provider: aws-eks
  cluster-region: us-east-1
  tier: primary
