apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - patch-gpu.yaml

namePrefix: gcp-
commonLabels:
  cluster-provider: gcp-gke
  cluster-region: us-central1
  tier: failover-secondary
