apiVersion: v1
kind: Service
metadata:
  name: smart-manufacturing-service
  labels:
    app: smart-manufacturing
spec:
  type: NodePort
  selector:
    app: smart-manufacturing
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 30080