apiVersion: v1
kind: Service
metadata:
  name: smart-manufacturing-api
  namespace: smart-manufacturing
  labels:
    app: smart-manufacturing-api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: smart-manufacturing-api
